name: CI

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ppa-version:
          - stable
          - unstable
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo add-apt-repository -y ppa:neovim-ppa/${{ matrix.ppa-version }}
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends neovim scdoc lua-busted
    - name: Run the test suite
      run: script -ec "make test"
      env:
        TERM: dumb

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        brew update
        brew install neovim scdoc luarocks
        luarocks --local install busted
    - name: Run the test suite
      run: script typescript make test BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
      env:
        TERM: dumb

  nix:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v20
    - uses: actions/checkout@v3
    - name: Run the test suite
      run: script -ec "nix develop --check"
      env:
        TERM: dumb
    - name: Update the fake inputs
      run: nix flake update
    - name: Run the test suite again
      run: script -ec "nix develop --check"
      env:
        TERM: dumb
    - name: Run the test suite with nightly neovim
      run: script -ec "nix develop --check '.#nightly'"
      env:
        TERM: dumb
